services:
    php:
        build:
            context: ./docker/php
            args:
                phpunit_version: 11.4.3
        working_dir: /app
        volumes:
            - '.:/app'
        environment:
            DATABASE_URL: postgres://florian:flodev@db:5432/todo_list
        depends_on:
            - db

    db:
        image: postgres:14
        environment:
            POSTGRES_USER: florian
            POSTGRES_PASSWORD: flodev
            POSTGRES_DB: todo_list
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
