version: '3.9'

services:
    php:
        build:
            context: ./docker/php
            args:
                phpunit_version: 11.4.3
        working_dir: /app
        volumes:
            - '.:/app'
        user: '${UID:-1000}:${GID:-1000}'
