frontend:
    path: /{reactRouting}
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: '/frontend/index.html'
        reactRouting: .*
